#!/bin/bash

## Created By Aditya Shakya

MENU="$(rofi -sep "|" -dmenu -i -p 'System' -location 3 -yoffset 32 -xoffset -20 -width 18 -hide-scrollbar -line-padding 4 -padding 20 -lines 4 -font "Termsyn 12" <<< "Lock|Logout|Reboot|Shutdown|Suspend")"
            case "$MENU" in
                *Lock) i3lock-fancy ;;
                *Logout) i3-msg exit;;
                *Reboot) systemctl reboot ;;
                *Shutdown) systemctl -i poweroff;;
                *Suspend) systemctl suspend
            esac
